name = "Warm Winter"
description = "A bare bones dark theme with some color tweakability"
license = "MIT"

homepage = "https://github.com/MattyRad/zola-warm-winter"

min_version = "0.4.0"

# An optional live demo URL
demo = "https://mattyrad.github.io/zola-warm-winter/"

[extra]

[author]
name = "Matt Radford"
homepage = "https://mradford.com"
